import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar is generated from the docs/ directory structure; sections are
// ordered by _category_.json position and pages by sidebar_position frontmatter.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
